
Calling foo raised an error - ValueError: Omg. Provided arguments: (300,)
